### ISSUE TITLE
rloadest issue for R version 3.3.0

### ISSUE THREAD

**Issue by echriste1950** [USGS-R/rloadest#11]
Help? I updated to R x64 v.3.3.0 and when I try and call rlodest I get the following error:

Loading required package: smwrStats
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘leaps’
Error: package ‘smwrStats’ could not be loaded

And if I try and install the smwrStats package I get this error:
> install.packages("smwrStats")
Warning in install.packages : package ‘smwrStats’ is not available (for R version 3.3.0)

**Comment by ldecicco-USGS** [comment]
Can you try this and let me know what you see. First restart R (close and open RStudio). Then:

```
install.packages("rloadest", repos="http://owi.usgs.gov/R")
```

**Comment by echriste1950** [comment]
Same result:
> install.packages("rloadest", repos="http://owi.usgs.gov/R")
trying URL 'http://owi.usgs.gov/R/bin/windows/contrib/3.3/rloadest_0.4.3.zip'
Content type 'application/x-zip-compressed' length 4189018 bytes (4.0 MB)
downloaded 4.0 MB

package ‘rloadest’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\echriste\AppData\Local\Temp\1\Rtmp0OA3bf\downloaded_packages
> library(rloadest)
Loading required package: smwrBase
Loading required package: lubridate
Loading required package: smwrGraphs
This information is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely best science. The information has not received final approval by the U.S. Geological Survey (USGS) and is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the information. Although this software program has been used by the USGS, no warranty, expressed or implied, is made by the USGS or the U.S. Government as to the accuracy and functioning of the program and related program material nor shall the fact of distribution constitute any such warranty, and no responsibility is assumed by the USGS in connection therewith.
Loading required package: smwrStats
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘leaps’
Error: package ‘smwrStats’ could not be loaded

**Comment by ldecicco-USGS** [comment]
Try installing the leaps package first, then install smwrStats. It actually looks to me like rloadest installed OK:

```
install.packages("leaps")

install.packages("smwrStats", repos="http://owi.usgs.gov/R")
```

That can happen when a package that a package depends on adds a new dependency....the install only checks the first layer of dependencies.....

Ow...my head!

**Comment by echriste1950** [comment]
Sorry, had to go to a going away lunch. Anyway:

> install.packages("leaps")
Warning message:
package ‘leaps’ is not available (for R version 3.3.0)

**Comment by ldecicco-USGS** [comment]
I'm not sure what CRAN mirror you are using, but I'd recommend changing it to RStudio's "cloud" hosted one:

```
chooseCRANmirror()

HTTPS CRAN mirror 

 1: 0-Cloud [https]                2: Austria [https]             
 ...
Selection: 1
```

Then try again (because it seems like you are on Windows, and there should be a leaps package available for 3.3 (it just worked for me at least from that mirror).

**Comment by echriste1950** [comment]
So that worked initially, but then I started hitting other missing packages (dependencies?) that i was able to install  until this:

> library(rloadest)
Loading required package: smwrQW
Loading required package: dataRetrieval
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘coin’
Error: package ‘smwrQW’ could not be loaded
> install.packages("smwrQW")
Warning in install.packages :
  package ‘smwrQW’ is not available (for R version 3.3.0)
> install.packages("coins")
Warning in install.packages :
  package ‘coins’ is not available (for R version 3.3.0)

Note(I also tried reinstalling rloadest)

**Comment by ldecicco-USGS** [comment]
After changing your CRAN mirror, maybe you need to restart R? Try restarting and then try installing the `coins` package. I just worked on my R 3.3...if it doesn't work, paste what you get from:

```
devtools::session_info()
```

**Comment by echriste1950** [comment]
Missing Rtools?

> install.packages("coins")
Warning message:
package ‘coins’ is not available (for R version 3.3.0) 
> devtools::session_info()
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.3.0 was found. (Only the following incompatible version(s) of Rtools were found:3.2)

Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/ and then run find_rtools().
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2016-05-31                  

Packages -----------------------------------------------------------------------
 package  * version date       source        
 devtools   1.9.1   2015-09-11 CRAN (R 3.1.3)
 digest     0.6.9   2016-01-08 CRAN (R 3.1.3)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.0)

**Comment by echriste1950** [comment]
Downloading Rtools now. May have to get IT to install.

**Comment by echriste1950** [comment]
After (re)installing Rtools And rloadest I got it working, but I still had
to individually install a bunch of dependent packages.

Thanks for your help - I think I learned a thing or two.

Eric D Christensen
USGS-Missouri WSC
401 NW Capital Drive
Lee's Summit. MO 64086
Phone: 816.554.3489 Ext. 204
FAX: 816.554.9273

**Comment by ldecicco-USGS** [comment]
Phew...not sure what exactly was trouble, but I had a whole other set of problem when I upgraded to 3.3. These major upgrades are always a bit tricky.
