### ISSUE TITLE
I can not install the package!

### ISSUE THREAD

**Issue by cnlhm** [USGS-R/rloadest#12]
I can not install the rloadest. The following are the information about the installment. I do not know the reason! Who can help me intall it? Thanks. My couputer environment is R studio Version 0.99.902. 

> install.packages("rloadest", repos="http://owi.usgs.gov/R")
> Installing package into ‘C:/Users/hmlu/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> Package which is only available in source form, and may need compilation of C/C++/Fortran:
>   ‘rloadest’
> Do you want to attempt to install these from sources?
> y/n: y
> installing the source package ‘rloadest’

trying URL 'http://owi.usgs.gov/R/src/contrib/rloadest_0.4.3.tar.gz'
Content type 'application/x-tar' length 4100850 bytes (3.9 MB)
downloaded 3.9 MB
- installing _source_ package 'rloadest' ...
  *\* libs

**\* arch - i386
gfortran -m32     -O3  -mtune=core2 -c DLNGAM.f -o DLNGAM.o
gfortran -m32     -O3  -mtune=core2 -c EXPON.f -o EXPON.o
gfortran -m32     -O3  -mtune=core2 -c EXPVAR.f -o EXPVAR.o
gfortran -m32     -O3  -mtune=core2 -c LOAD95CI.f -o LOAD95CI.o
gfortran -m32     -O3  -mtune=core2 -c LOADSEP.f -o LOADSEP.o
gfortran -m32     -O3  -mtune=core2 -c SQUARE.f -o SQUARE.o
gfortran -m32     -O3  -mtune=core2 -c TACIT_LOADS.f -o TACIT_LOADS.o
gfortran -m32     -O3  -mtune=core2 -c TAC_LOAD.f -o TAC_LOAD.o
gfortran -m32     -O3  -mtune=core2 -c estlday.f -o estlday.o
gfortran -m32     -O3  -mtune=core2 -c estltot.f -o estltot.o
gcc -m32 -shared -s -static-libgcc -o rloadest.dll tmp.def DLNGAM.o EXPON.o EXPVAR.o LOAD95CI.o LOADSEP.o SQUARE.o TACIT_LOADS.o TAC_LOAD.o estlday.o estltot.o -Ld:/RCompile/r-compiling/local/local320/lib/i386 -Ld:/RCompile/r-compiling/local/local320/lib -lgfortran -LC:/PROGRA~1/R/R-32~1.0/bin/i386 -lR
installing to C:/Users/hmlu/Documents/R/win-library/3.2/rloadest/libs/i386

**\* arch - x64
gfortran -m64     -O2  -mtune=core2 -c DLNGAM.f -o DLNGAM.o
gfortran -m64     -O2  -mtune=core2 -c EXPON.f -o EXPON.o
gfortran -m64     -O2  -mtune=core2 -c EXPVAR.f -o EXPVAR.o
gfortran -m64     -O2  -mtune=core2 -c LOAD95CI.f -o LOAD95CI.o
gfortran -m64     -O2  -mtune=core2 -c LOADSEP.f -o LOADSEP.o
gfortran -m64     -O2  -mtune=core2 -c SQUARE.f -o SQUARE.o
gfortran -m64     -O2  -mtune=core2 -c TACIT_LOADS.f -o TACIT_LOADS.o
gfortran -m64     -O2  -mtune=core2 -c TAC_LOAD.f -o TAC_LOAD.o
gfortran -m64     -O2  -mtune=core2 -c estlday.f -o estlday.o
gfortran -m64     -O2  -mtune=core2 -c estltot.f -o estltot.o
gcc -m64 -shared -s -static-libgcc -o rloadest.dll tmp.def DLNGAM.o EXPON.o EXPVAR.o LOAD95CI.o LOADSEP.o SQUARE.o TACIT_LOADS.o TAC_LOAD.o estlday.o estltot.o -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -lgfortran -LC:/PROGRA~1/R/R-32~1.0/bin/x64 -lR
installing to C:/Users/hmlu/Documents/R/win-library/3.2/rloadest/libs/x64
*\* R
*\* data
**\* moving datasets to lazyload DB
*\* demo
*\* inst
*\* preparing package for lazy loading
Warning: package 'smwrBase' was built under R version 3.2.3
Warning: package 'lubridate' was built under R version 3.2.5
Warning: package 'smwrGraphs' was built under R version 3.2.3
Warning: package 'smwrStats' was built under R version 3.2.3
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'pbkrtest'
Error : package 'smwrStats' could not be loaded
ERROR: lazy loading failed for package 'rloadest'
- removing 'C:/Users/hmlu/Documents/R/win-library/3.2/rloadest'
  Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" CMD INSTALL -l "C:\Users\hmlu\Documents\R\win-library\3.2" C:\Users\hmlu\AppData\Local\Temp\RtmpqE2aud/downloaded_packages/rloadest_0.4.3.tar.gz' had status 1
  Warning in install.packages :
  installation of package ‘rloadest’ had non-zero exit status

The downloaded source packages are in
    ‘C:\Users\hmlu\AppData\Local\Temp\RtmpqE2aud\downloaded_packages’

> install.packages("pbkrtest")
> Installing package into ‘C:/Users/hmlu/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘pbkrtest’ is not available (for R version 3.2.0)

**Comment by ldecicco-USGS** [comment]
I'm not sure why it's not letting you install `pbkrtest`....maybe try specifying the "cloud" repo for CRAN (always the most stable):


```
install.packages("pbkrtest", repos = "https://cloud.r-project.org")

```

Let me know if that helps.
