### ISSUE TITLE
Presentation of rloadest output in manuscripts

### ISSUE THREAD

**Issue by AllisonOliver** [USGS-R/rloadest#13]
Hello all!

Question about publishing results from rloadest... Aside from load numbers, the model selected, and the number of samples, what additional diagnostics from a rloadest run are good practice to include in a manuscript (thinking supplementary material here)? In other words, what would the readers be interested in regarding interpreting the performance of the model?

Thank you for your help!

Allison

**Comment by aappling-usgs** [comment]
Hi Allison,
Have you seen Hirsch, R. M. 2014. Large biases in regression-based constituent flux estimates: causes and diagnostic tools. Journal of the American Water Resources Association 50:1401–1424, DOI: 10.1111/jawr.12195? Lots of good suggestions in there.
Best,
Alison

**Comment by AllisonOliver** [comment]
Thanks, Alison.  I had not seen that.  Great suggestion.
