### ISSUE TITLE
tibble input data breaks loadReg

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/rloadest#18]
When you supply a tibble for the input data, `loadReg` breaks in these lines https://github.com/USGS-R/rloadest/blob/master/R/loadReg.R#L113-L119 at the `range(Time)` call, since range needs a vector but is given a df instead.  

This is avoidable by making sure you supply an old-school data frame though.

**Comment by ldecicco-USGS** [comment]
Want to submit a pr to fix it?

**Comment by wdwatkins** [comment]
yeah I'll put it on my list for later
