### ISSUE TITLE
rloadest issue for R version 3.4.0

### ISSUE THREAD

**Issue by emorway-usgs** [USGS-R/rloadest#23]
This is likely related to issue #11...

I was recently forced to install a new OS (win10) and am going through the process of getting everything put back together the way I like it.  In trying to reestablish R (R x64 v.3.3.0) and various R libraries on my machine, I get the following error when trying to install rloadest:

`install.packages("rloadest", repos="http://owi.usgs.gov/R", lib='C:/Program Files/R/R-3.4.0/library/')`

`Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
missing value where TRUE/FALSE needed` 

if I instead reduce this command to `install.packages("rloadest")` and try to go through the CRAN mirror, I get:

`--- Please select a CRAN mirror for use in this session ---`

`Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : missing value where TRUE/FALSE needed` 
`In addition: Warning message: package ‘rloadest’ is not available (for R version 3.4.0)`

It would seem then that there are two issues?  Is there a repo I should be using in `install.packages()` that has a version of rloadest available for R 3.4.0?  As for the other error message, I'm clueless.  Has anyone successfully installed rloadest with R 3.4.0

**Comment by aappling-usgs** [comment]
That error is associated with a known issue with R version 3.4.0: https://stackoverflow.com/questions/44054022/installing-package-is-failing-with-error-in-if-file-existsdest-file-mtime

There's a patched version of R available: https://cran.r-project.org/bin/windows/base/rpatched.html

**Comment by emorway-usgs** [comment]
This error went away with the update to 3.4.1.  Sorry for the trouble

**Comment by aappling-usgs** [comment]
No worries, thanks for following up
