### ISSUE TITLE
Passing model number as a variable

### ISSUE THREAD

**Issue by jsta** [USGS-R/rloadest#32]
I am trying to pass a model number as a variable like so:

```
my_model_no <- 1
loadreg_mod <- loadReg(as.formula(paste0("Phosphorus ~ model(", my_model_no, ")")),
          data = app1.calib, dates = "DATES", flow = "FLOW")
```

but I get the following error:

> Error in m[["formula"]][[3L]] : subscript out of bounds

The only way I was able to get my code to run was to modify `R/loadReg.R` by adding the line:
```r
m[["formula"]] <- eval(m[["formula"]])
```

As far as I can tell this change [doesn't create any differences in model results](https://gist.github.com/jsta/4b8be3f41da11ee11c08523cba73c129) compared to the typical non-variable approach. It does however create differences in the  `loadreg_mod$cfit$call` that _probably_ doesn't cause any downstream errors.

Is there another way to pass model numbers as variables? If not, would a PR be welcome?

**Comment by ldecicco-USGS** [comment]
I think that sounds good. Feel free to submit a PR, that would be great!

**Comment by jsta** [comment]
Feature added in #34
