### ISSUE TITLE
Rloadest user demo, how to finish code on line 14?

### ISSUE THREAD

**Issue by AllisonOliver** [USGS-R/rloadest#4]
Hi.  I'm trying to run through the user demo for rloadest for BatchLoads and after setting the units on line 14 it is telling me the code isn't complete... e.g. gives me the "+" sign in Rstudio.  Is there something missing here?  Or am I missing something?  Thank you.

**Comment by aappling-usgs** [comment]
Hi Allison,
Could you please (1) try again with a fresh RStudio session, and (2) once you hit the error, copy and paste everything from the console (commands, output, and errors) into a new comment in this thread? That will help in debugging.
Thanks,
Alison

PS - In case you haven't seen this before, you can format code nicely in GitHub using three backticks on their own line, followed by the lines of code, followed by three more backticks on their own line.

**Comment by AllisonOliver** [comment]
Here is what I get... no "error" per say to start, but the "+" after assigning the units to loads.. then some errors begin below. 

'''
> Staids <- c("MISS AT Clinton" = "05420500")
> Params <- c("00631")
> Start <- "2000-10-01"
> End <- "2006-09-30"
> Loads <- "water year"
> ld.sfx <- "wy"
> ld.unt <- "kg”
+ library(dataRetrieval)
+ library(rloadest)
+ setwd(/Users/DrAllisonOliver/Documents/rloadest)
+ for(sta in Staids)   {
+ Qdata <- paste("Q", sta, sep="")
Error: unexpected symbol in:
"for(sta in Staids)   {
Qdata <- paste("Q"
> QWdata <- paste("QW", sta, sep="")
Error in paste("QW", sta, sep = "") : object 'sta' not found
'''

**Comment by aappling-usgs** [comment]
I think I spy a curly double-quote on the right side of `kg` in `ld.unt <- "kg”`. R is really picky about those - you need simple double quotes (`"` instead of `”`) at all times.

**Comment by aappling-usgs** [comment]
PS - thanks for using GitHub to ask this question. It's great to have these problems and solutions out in the open in case someone else runs into the same issues.

**Comment by AllisonOliver** [comment]
Aha!  Grrrrrr.. this was copy and pasted directly off the Github demo.  I don't understand why that happens.  Oh well... thank you for taking the time to answer such a beginner question :)
