### ISSUE TITLE
How to import non-NWIS data to run in rloadest?

### ISSUE THREAD

**Issue by AllisonOliver** [USGS-R/rloadest#5]
Hello.  I am trying to use rloadest to calculate loads for a dataset that does NOT come from the NWIS database.  I am having a difficult time trying to apply the code and information from the vignettes to importing and running the commands on my own dataset... for example, how do I want my data should be set up, the headers for the columns, etc. I tried to match up the way my dataset looks with some of the USGS files downloaded from the vignettes but didn't have much luck.  Any advice?  Thank you.

**Comment by dlorenz-usgs** [comment]
It is difficult to answer this question without specifics on what your dataset looked like and the calls to loadReg and predLoad. The functions in rloadest were designed to be extremely flexible for model building, much like lm--the minimum requirements to build a calibration data set are 3 columns: the constituent, dates with or without times, and flow. The names of those constituents can be any valid R name. If the constituent is censored, then you would also need all of the information pertinent to the censoring information, ideally the detection limit and some indicator of the value being censored. For that latter case, you'd use the as.lcens function to construct the response variable or construct a naming convention and use the convert2qw function as demonstrated in vignette application 4.
  For prediction, the minimum columns are dates and flow and the column names must match those in the calibration data.
