### ISSUE TITLE
Size limit for rows in predLoad

### ISSUE THREAD

**Issue by AllisonOliver** [USGS-R/rloadest#7]
Hi.  I am trying to run two years worth of data that has flow at 5-minute increments.  Preload will not let me do this because of a size limit for rows... is there another way to handle this without splitting up the years and still keep the 5-minute flow intervals?   Here is the error:

>Error in predLoad(tmp.lr, newdata = Qdata, load.units = "kg", by = "month",  : 
  newdata has too many rows, the size limit is 176000

Thanks.

**Comment by ldecicco-USGS** [comment]
Unfortunately, that is a limit due to the way R interacts with the Fortran code. One recommendation is to split up the load calculations into water years (or calendar if that is what you are interested), and run those year-by-year, then use the `rbind` function to put them together at the end.

**Comment by AllisonOliver** [comment]
Thank you.  I am currently running them split by water year, but my hope was to run them together to increase my sample size (working with 15-25 samples per year).  Thanks for the help!
